server:
  applicationConnectors:
    - type: http
      port: 8989
      # for security reasons bind to localhost
      bindHost: localhost
  adminConnectors:
    - type: http
      port: 8990
      bindHost: localhost

logging:
  level: WARN
  appenders:
    - type: console
#    - type: file
#      logFormat: "%-5p %c: %m%n%rEx"
#      currentLogFilename: bug.log
#      archivedLogFilenamePattern: bug-%d.log.gz
#      archivedFileCount: 5
